on:
  - push

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: python -m install -r requirements-dev.txt

      - name: Excute tests
        run: pytest
        env: 
          HEADLESS:1
